//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualProvision.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualProvision.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string ActionBar_Item_Logout {
            get {
                return ResourceManager.GetString("ActionBar_Item_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check your  key value {0} on AppSettings and rebuild the application..
        /// </summary>
        internal static string AppSettings_InvalidSetting_Message {
            get {
                return ResourceManager.GetString("AppSettings_InvalidSetting_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid app setting.
        /// </summary>
        internal static string AppSettings_InvalidSetting_Title {
            get {
                return ResourceManager.GetString("AppSettings_InvalidSetting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        internal static string Common_Next_Button {
            get {
                return ResourceManager.GetString("Common_Next_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need a camera to use this application..
        /// </summary>
        internal static string Dialog_CameraNotAvailable_Message {
            get {
                return ResourceManager.GetString("Dialog_CameraNotAvailable_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera not available.
        /// </summary>
        internal static string Dialog_CameraNotAvailable_Title {
            get {
                return ResourceManager.GetString("Dialog_CameraNotAvailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all permissions are granted. The app will not work..
        /// </summary>
        internal static string Dialog_CheckPermissions_Message {
            get {
                return ResourceManager.GetString("Dialog_CheckPermissions_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions error.
        /// </summary>
        internal static string Dialog_CheckPermissions_Title {
            get {
                return ResourceManager.GetString("Dialog_CheckPermissions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Internet conection..
        /// </summary>
        internal static string Dialog_Connectivity_Message {
            get {
                return ResourceManager.GetString("Dialog_Connectivity_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Dialog_Connectivity_Title {
            get {
                return ResourceManager.GetString("Dialog_Connectivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        internal static string Dialog_CredentialsError_Message {
            get {
                return ResourceManager.GetString("Dialog_CredentialsError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        internal static string Dialog_CredentialsError_Title {
            get {
                return ResourceManager.GetString("Dialog_CredentialsError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear your credentials?.
        /// </summary>
        internal static string Dialog_Logout_Message {
            get {
                return ResourceManager.GetString("Dialog_Logout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Dialog_Logout_Title {
            get {
                return ResourceManager.GetString("Dialog_Logout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem, please retake the photo.
        /// </summary>
        internal static string Dialog_PhotoFailed_Message {
            get {
                return ResourceManager.GetString("Dialog_PhotoFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Dialog_PhotoFailed_Title {
            get {
                return ResourceManager.GetString("Dialog_PhotoFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App needs all the permissions in order to work..
        /// </summary>
        internal static string Dialog_RequiredPermissions_Message {
            get {
                return ResourceManager.GetString("Dialog_RequiredPermissions_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Dialog_RequiredPermissions_Title {
            get {
                return ResourceManager.GetString("Dialog_RequiredPermissions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error from the server, please check your configuration settings..
        /// </summary>
        internal static string Dialog_ServiceError_Message {
            get {
                return ResourceManager.GetString("Dialog_ServiceError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration.
        /// </summary>
        internal static string Dialog_ServiceError_Title {
            get {
                return ResourceManager.GetString("Dialog_ServiceError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        internal static string LoginPage_ClientId_Label {
            get {
                return ResourceManager.GetString("LoginPage_ClientId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string LoginPage_Login_Button {
            get {
                return ResourceManager.GetString("LoginPage_Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPage_Password_Label {
            get {
                return ResourceManager.GetString("LoginPage_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant ID.
        /// </summary>
        internal static string LoginPage_TenantId_Label {
            get {
                return ResourceManager.GetString("LoginPage_TenantId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your credentials.
        /// </summary>
        internal static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo.
        /// </summary>
        internal static string MediaPage_Title {
            get {
                return ResourceManager.GetString("MediaPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPLOY.
        /// </summary>
        internal static string ResourceGroupPage_Deploy_Button {
            get {
                return ResourceManager.GetString("ResourceGroupPage_Deploy_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New resource group name.
        /// </summary>
        internal static string ResourceGroupPage_NewResourceGroup_Label {
            get {
                return ResourceManager.GetString("ResourceGroupPage_NewResourceGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new resource group name.
        /// </summary>
        internal static string ResourceGroupPage_NewResourceGroup_Placeholder {
            get {
                return ResourceManager.GetString("ResourceGroupPage_NewResourceGroup_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resource group found with this name.
        /// </summary>
        internal static string ResourceGroupPage_ResourceGroup_EmptyText {
            get {
                return ResourceManager.GetString("ResourceGroupPage_ResourceGroup_EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource group.
        /// </summary>
        internal static string ResourceGroupPage_ResourceGroup_Label {
            get {
                return ResourceManager.GetString("ResourceGroupPage_ResourceGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a resource group.
        /// </summary>
        internal static string ResourceGroupPage_ResourceGroup_Placeholder {
            get {
                return ResourceManager.GetString("ResourceGroupPage_ResourceGroup_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string ResourceGroupPage_SelectRegion_Label {
            get {
                return ResourceManager.GetString("ResourceGroupPage_SelectRegion_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a region.
        /// </summary>
        internal static string ResourceGroupPage_SelectRegion_PickerTitle {
            get {
                return ResourceManager.GetString("ResourceGroupPage_SelectRegion_PickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select region and resource group.
        /// </summary>
        internal static string ResourceGroupPage_SelectRegion_Text {
            get {
                return ResourceManager.GetString("ResourceGroupPage_SelectRegion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment options.
        /// </summary>
        internal static string ResourceGroupPage_Title {
            get {
                return ResourceManager.GetString("ResourceGroupPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to use an existing resource group.
        /// </summary>
        internal static string ResourceGroupPage_WantToUseAnExistingRg_Label {
            get {
                return ResourceManager.GetString("ResourceGroupPage_WantToUseAnExistingRg_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        internal static string ResultsPage_Done_Button {
            get {
                return ResourceManager.GetString("ResultsPage_Done_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment progress.
        /// </summary>
        internal static string ResultsPage_Title {
            get {
                return ResourceManager.GetString("ResultsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} services found.
        /// </summary>
        internal static string Services_Recognition_ManyFound {
            get {
                return ResourceManager.GetString("Services_Recognition_ManyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No services found. Please try again..
        /// </summary>
        internal static string Services_Recognition_NotFound {
            get {
                return ResourceManager.GetString("Services_Recognition_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One service found.
        /// </summary>
        internal static string Services_Recognition_OneFound {
            get {
                return ResourceManager.GetString("Services_Recognition_OneFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognizing Services ....
        /// </summary>
        internal static string Services_Recognition_Working {
            get {
                return ResourceManager.GetString("Services_Recognition_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string ServicesPage_Title {
            get {
                return ResourceManager.GetString("ServicesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string SubscriptionPage_Refresh_Label {
            get {
                return ResourceManager.GetString("SubscriptionPage_Refresh_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Azure subscription.
        /// </summary>
        internal static string SubscriptionPage_TargetSubscription_Label {
            get {
                return ResourceManager.GetString("SubscriptionPage_TargetSubscription_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a subscription.
        /// </summary>
        internal static string SubscriptionPage_TargetSubscription_PickerTitle {
            get {
                return ResourceManager.GetString("SubscriptionPage_TargetSubscription_PickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your subscription.
        /// </summary>
        internal static string SubscriptionPage_Title {
            get {
                return ResourceManager.GetString("SubscriptionPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field could not be empty..
        /// </summary>
        internal static string Validations_NullOrEmptyMessage {
            get {
                return ResourceManager.GetString("Validations_NullOrEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given resource name already exists in your subscription!.
        /// </summary>
        internal static string Validations_ResourceGroup_DuplicatedName {
            get {
                return ResourceManager.GetString("Validations_ResourceGroup_DuplicatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name: use alphanumeric, underscore, parentheses, hyphen, period (except at end).
        /// </summary>
        internal static string Validations_ResourceGroup_InvalidName {
            get {
                return ResourceManager.GetString("Validations_ResourceGroup_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should specify a resource group name.
        /// </summary>
        internal static string Validations_ResourceGroup_RequiredName {
            get {
                return ResourceManager.GetString("Validations_ResourceGroup_RequiredName", resourceCulture);
            }
        }
    }
}
